spring.application.name=userservice
# PostgreSQL Database URL connection string
spring.datasource.url=jdbc:postgresql://localhost:5432/MacLoc

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=1234

# PostgreSQL Driver Class Name (Optional in newer Spring Boot versions, but good practice)
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable DDL Auto Update
spring.jpa.hibernate.ddl-auto=update

server.error.include-stacktrace=always
server.error.include-message=always

debug=true
logging.level.org.springframework=DEBUG
logging.level.root=INFO